const images = import.meta.glob(['../image/bg/*.jpg', '../image/optimized/*.webp'], {
  eager: true,
  query: '?url',
  import: 'default',
})
export function asset(path) {
  const url = images[`../image/${path}`]
  if (!url) throw new Error(`Missing image: ${path}`)
  return url
}
export const links = {
  bilibili: 'https://space.bilibili.com/3537114702547033',
  github: 'https://github.com/lihaoyuan114',
  releases: 'https://github.com/QinglanStudio/QinglanStudioOfficialWeb/releases',
}
export const projects = [
  {
    name: 'RunForYourLife',
    category: '游戏',
    kind: '3D · 第一人称逃脱',
    description: '走进后室，在未知的空间里寻找出口。紧张感，来自下一个转角。',
    mark: 'RUN',
    tone: 'lime',
  },
  {
    name: 'CirDom 1 & 2',
    category: '游戏',
    kind: '4K 音游 · Python / Tkinter',
    description: '让节奏落在指尖。支持自行制谱，把喜欢的音乐变成自己的关卡。',
    mark: '4K',
    tone: 'purple',
  },
  {
    name: '1955',
    category: '游戏',
    kind: '第一人称 · 跑酷',
    description: '逃离番茄，一路向前。在精心排列的线性关卡中寻找节奏。',
    mark: '1955',
    tone: 'peach',
  },
  {
    name: 'Pong:Re',
    category: '游戏',
    kind: '经典重制 · 街机',
    description: '熟悉的球拍与小球，配上现代 UI 和动画，再来一局。',
    mark: 'PONG',
    tone: 'blue',
  },
  {
    name: '番茄大陆冒险传',
    category: '游戏',
    kind: 'RPG · 弹幕 / 回合制',
    description: '把弹幕躲避与回合制战斗放进同一场冒险。',
    mark: 'RPG',
    tone: 'peach',
  },
  {
    name: '塞尔达传说_奇幻森林',
    category: '游戏',
    kind: '同人 · 冒险',
    description: '以初代《塞尔达传说》为灵感的同人作品。',
    mark: 'FOREST',
    tone: 'lime',
  },
  {
    name: '极限竞速',
    category: '游戏',
    kind: '开放世界 · 赛车',
    description: '在开放世界里探索驾驶的乐趣。',
    mark: 'DRIVE',
    tone: 'blue',
  },
  {
    name: '傀儡战争',
    category: '游戏',
    kind: '同人 · 游戏改编',
    description: '将 skibid toilet 同人作品「傀儡战争」带进游戏世界。',
    mark: 'WAR',
    tone: 'purple',
  },
  {
    name: 'EncryptMessage',
    category: '软件',
    kind: 'Python · 消息工具',
    description: '使用原创算法的消息加密实验，探索文字的另一种表达方式。',
    mark: '{ }',
    tone: 'lime',
  },
  {
    name: 'WechatAutoResponse',
    category: '软件',
    kind: 'Python · 自动回复',
    description: '一个用 Python 编写的微信自动回复工具。',
    mark: 'REPLY',
    tone: 'blue',
  },
  {
    name: 'KawaiCmd',
    category: '软件',
    kind: '终端 · 界面',
    description: '重新设计 CMD 的 UI，让输出语言风格可以自由配置。',
    mark: '> _',
    tone: 'purple',
  },
  {
    name: 'CCB 生成器',
    category: '软件',
    kind: '文字 · 检索',
    description: '遍历中文字库，生成 CCB 组合，并支持快速查找。',
    mark: 'CCB',
    tone: 'peach',
  },
  {
    name: 'Takeuchi_Ayaka',
    category: 'AI',
    kind: 'Qwen1.5-4B · Live2D',
    description: '我们的「女鹅」：互动式二次元语言模型，连接 Python 后端与 Unity Live2D。',
    mark: 'AYAKA',
    tone: 'purple',
  },
  {
    name: 'ImageReconization',
    category: 'AI',
    kind: 'OpenCV · 图像识别',
    description: '女鹅的附属模型，用级联识别器识别画面中的元素。',
    mark: '[◎]',
    tone: 'blue',
  },
  {
    name: 'SelfAskSelfAnswer',
    category: 'AI',
    kind: '对话 · 生成',
    description: '让两个角色持续对话，自由设定人设、背景和相遇的事件。',
    mark: 'TALK',
    tone: 'lime',
  },
  {
    name: 'AnswerGenerater',
    category: 'AI',
    kind: 'Qwen1.5-4B · 批量生成',
    description: '探索语言模型批量生成不同回答的能力。',
    mark: 'A+',
    tone: 'peach',
  },
  {
    name: 'FastClicker',
    category: '实验',
    kind: 'Python · 自动化',
    description: '用 Python 编写的连点器，探索自动化输入。',
    mark: 'CLICK',
    tone: 'blue',
  },
  {
    name: '死神之镰',
    category: '实验',
    kind: 'Python · 安全研究',
    description: '原站收录的远程命令与鼠标控制实验。仅展示项目介绍。',
    mark: 'LAB',
    tone: 'purple',
  },
  {
    name: '刷屏脚本',
    category: '实验',
    kind: 'Python · 自动化',
    description: '原站收录的自动化文字输入实验。仅展示项目介绍。',
    mark: 'TEXT',
    tone: 'peach',
  },
  {
    name: 'TLhack',
    category: '实验',
    kind: 'Minecraft · 脚本',
    description: '原站收录的 Minecraft 操作自动化实验。仅展示项目介绍。',
    mark: 'MC',
    tone: 'lime',
  },
  {
    name: '弹窗实验',
    category: '实验',
    kind: '窗口 · 安全研究',
    description: '原站「弹窗病毒」项目档案，记录窗口与资源占用实验。仅展示项目介绍。',
    mark: 'WIN',
    tone: 'blue',
  },
  {
    name: '逃离后室自动打字脚本',
    category: '实验',
    kind: '游戏 · 自动化',
    description: '为游戏《逃离后室》编写的自动打字脚本。',
    mark: 'TYPE',
    tone: 'purple',
  },
]
export const members = [
  {
    name: '青岚_leo',
    role: '创始人 / 程序 / 设计',
    image: '青岚_leo.webp',
    text: '热情和灵感的源头。想法太多，偶尔也会在不同项目之间来回跳跃。',
  },
  {
    name: '苏醒cn',
    role: '美术',
    image: '苏醒cn.webp',
    text: '负责让想象变得可见。偶尔神秘消失，非常喜欢萨卡班甲鱼。',
  },
  {
    name: 'zdbcn',
    role: '创意 / 测试',
    image: 'zdbcn.webp',
    text: '什么都能做一点。提供灵感、修改意见，也负责帮大家找出问题。',
  },
  {
    name: '「空白」',
    role: '剧情 / 创意 / 工具',
    image: 'zcr.webp',
    text: '是的，名字就是空白。负责灵感与剧情，偶尔提供工具支持。',
  },
]
export const supporters = [
  { name: '...', image: 'Lu.webp', text: '「傀儡战争」原作者，为游戏提供剧情和美术支持。' },
  {
    name: 'wanglan',
    image: 'WangLan.webp',
    text: '为早期项目「Nemo 审判战」提供灵感、玩法设计并参与制作。',
  },
]
export const wallpapers = [
  ['xy', '小鸟游星野'],
  ['ylb', '伊吕波'],
  ['rn', '空崎日奈'],
  ['tzxd', '兔子小队'],
  ['fll', '芙莉莲'],
  ['cywl', '初音未来'],
  ['xya', '星野爱'],
  ['myn', '猫雨雫'],
  ['gl', '古拉'],
  ['stl', '山田凉'],
  ['vrt', '维尔汀'],
].map(([id, name]) => ({ id, name }))
